"""add hnsw cosine index on processed_articles embedding

Revision ID: e03d1a74c15a
Revises: bd938445583d
Create Date: 2026-10-02 12:20:44.054825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e03d1a74c15a'
down_revision: Union[str, None] = 'bd938445583d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Blocks writes to processed_articles while it builds (under a second for ~1k rows). On a large table,
    # build it with postgresql_concurrently=True inside op.get_context().autocommit_block() instead.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_processed_articles_embedding_hnsw', 'processed_articles', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_processed_articles_embedding_hnsw', table_name='processed_articles', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    # ### end Alembic commands ###
